name: Clear Cloudflare Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * 0'

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Purge Everything in Cloudflare Zone
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
      
      - name: Debug working directory
        run: |
          pwd
          ls -l
      
      - name: Update README with last Cloudflare cache clear date
        run: |
          DATE=$(date -u +"%Y--%m--%d%%20%H:%M%%20UTC")
          sed -i '/<img alt="Cloudflare Cache Clear" src="https:\/\/img.shields.io\/badge\/Cloudflare%20Cache%20Clear-.*-orange?logo=cloudflare&style=for-the-badge">/c\<img alt="Cloudflare Cache Clear" src="https://img.shields.io/badge/Cloudflare%20Cache%20Clear-'"$DATE"'-orange?logo=cloudflare&style=for-the-badge">' README.md
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "docs: update last Cloudflare cache clear date [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}