name: Update PROD Deployment to Latest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 7 * *'

jobs:
  switch-service-to-green:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go to green service (DR)
        run: |
          awk '{if (!done && $0 ~ /version:[[:space:]]*blue/) {sub(/version:[[:space:]]*blue/, "version: green"); done=1} print}' shared/nginx-service.yaml > tmp.yaml && mv tmp.yaml shared/nginx-service.yaml

      - name: Update README badge to green (DR)
        run: |
          sed -i 's|<img alt="Prod Silo" src="https://img.shields.io/badge/Prod%20Silo-.*-.*?style=for-the-badge">|<img alt="Prod Silo" src="https://img.shields.io/badge/Prod%20Silo-green-green?style=for-the-badge">|' README.md
      
      - name: Update blue deployment to latest
        run: |
          sed -i 's#technotuba/nginx:[^"]*#technotuba/nginx:latest#g' prod/nginx-blue.yaml
      
      - name: Update blue badge in README to latest
        run: |
          sed -E -i 's|(alt="Blue Image" src="https://img\.shields\.io/badge/blue--image-technotuba/nginx:)[^"-]*(\-blue\?style=for-the-badge&logo=docker&logoColor=white")|\1latest\2|' README.md
    
      - name: Commit and push updated YAMLs
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add shared/nginx-service.yaml prod/nginx-blue.yaml README.md
          git commit -m "chore: update deployment images to latest and previous" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
